mybatis:
    mapper-locations:
        - classpath:mapper/data*/*Mapper.xml
spring:
    datasource:
        data1:
            jdbc-url: jdbc:mysql://localhost:3306/api?useSSL=false
            password: qq1203943228
            username: root
            driver-class-name: com.mysql.cj.jdbc.Driver
        data2:
            jdbc-url: jdbc:mysql://localhost:3306/api?useSSL=false
            password: qq1203943228
            username: root
            driver-class-name: com.mysql.cj.jdbc.Driver
server:
    port: 8080